const fetch = require('node-fetch');

module.exports = async (context) => {
    const { client, m, text, botname } = context;

    if (!botname) {
        console.error(`Botname not set, you brain-dead fuck.`);
        return m.reply(`◈━━━━━━━━━━━━━━━━◈\n│❒ Bot’s fucked. No botname in context. Yell at your dev, dipshit.\n◈━━━━━━━━━━━━━━━━◈`);
    }

    if (!text) {
        return m.reply(`◈━━━━━━━━━━━━━━━━◈\n│❒ Yo, ${m.pushName}, you forgot the prompt, you dumb fuck! Example: .imagine a badass dragon burning shit.\n◈━━━━━━━━━━━━━━━━◈`);
    }

    const apiUrl = `https://api.giftedtech.web.id/api/ai/fluximg?apikey=gifted&prompt=${encodeURIComponent(text)}`;

    try {
        const response = await fetch(apiUrl);
        const data = await response.json();

        if (!data.success || !data.result) {
            return m.reply(`◈━━━━━━━━━━━━━━━━◈\n│❒ Fucking API failed, ${m.pushName}. No image for you, loser. Try again later.\n◈━━━━━━━━━━━━━━━━◈`);
        }

        const { creator, result } = data;
        const caption = `◈━━━━━━━━━━━━━━━━◈\n│❒ Generated by ${botname}, ‘cause ${m.pushName}’s too useless to draw shit.\n◈━━━━━━━━━━━━━━━━◈`;

        await client.sendMessage(
            m.chat,
            {
                image: { url: result },
                caption: caption
            },
            { quoted: m }
        );
    } catch (error) {
        console.error(`Image generation fucked up: ${error.stack}`);
        await m.reply(`◈━━━━━━━━━━━━━━━━◈\n│❒ Shit broke, ${m.pushName}. Couldn’t generate your stupid image. Try again, you moron.\n◈━━━━━━━━━━━━━━━━◈`);
    }
};